name: Deploy to GitHub Pages layadang.github.io repo

on:
  workflow_dispatch:

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Checkout pages repository
        uses: actions/checkout@v4
        with:
          repository: layadang/layadang.github.io
          token: ${{ secrets.PAT_PUSH_CONTENT }}
          path: laya-dang-pages-repo

      - name: Copy build folder into pages repo
        run: |
          cp -R build/* laya-dang-pages-repo/

      - name: Commit and push changes
        run: |
          cd laya-dang-pages-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy React build $(date)" || echo "No changes to commit"
          git push